### ISSUE TITLE
Sikertelen módosítások

### ISSUE THREAD

**Issue by vilmosnagy** [petergerner/alaptorveny#11]
Csak egy ötlet, de a sikertelen módosítási kísérleteket (amiket végül nem szavaztak meg), lehetne-e egy elutasított, s megcimkézett PR-ben gyűjteni? Cimke azért, hogy a többi, nem alkotmánymódosításhoz kötődő PR-től le lehessen majd szűrni később.

Amennyiben elfogadnátok egy ilyet, hétvégén megcsinálom a hetediket PR-nek. (http://www.parlament.hu/irom40/12458/12458.pdf)

Üdv,

**Comment by petergerner** [comment]
Jó ötlet, jöhet!

**Comment by raszi** [comment]
A hetediket már megcsinálta @orbanviktor lásd #10

**Comment by vilmosnagy** [comment]
ah, tényleg. mondjuk kaphatna rendes nevet, mert a címeket átfutva a #9 és a #10 ugyanolyan heccnek tűnik.

na, mindegy, hétvégén újra megkérem, meg lezárom, csak rendes névvel meg cimkével, ha nem gáz.

**Comment by raszi** [comment]
Szerintem csak újra kell nyitni a repo tulajdonosának. Ő át is tudja nevezni a PR nevét.

**Comment by petergerner** [comment]
kösz a tippet!
