### ISSUE TITLE
Népakarat mindenek felett

### ISSUE THREAD

**Issue by sarkiroka** [petergerner/alaptorveny#8]
- szerintem alkotmányban kellene megfogalmazni, hogy ne lehessen tömegek (a lakosság több mint 5%-a) bizalmával visszaélve nem teljesíteni az ígért / vállalt kötelezettségeket. az ilyen ember nem maradhat vezető pozícióban.
- ugyanígy azt is, hogy ne lehessen tömegek akaratával kifejezetten ellentétes dolgot tenni (a lakosság több mint 33%-a).
  - ha valami minden harmadik embernek nem megfelelő, az nem fogadható el szerintem. ez arra vonatkozik amikor a lakosság 33%-a kinyilatkoztatja akaratát.
- bele kellene fogalmazni azt is, hogy egy magyar embernek kötelessége tisztelnie a saját hazáját, annak jelképeit tilos megrongálni, jó hírnevét tilos lejáratni.

**Comment by meszaros-lajos-gyorgy** [comment]
Javasolnám a SCRUM bevezetését a parlamentbe. Daily standup-ok, 2 hetes sprintek, retrospective, ...

**Comment by petergerner** [comment]
Ez a Github, nem a Parlament. :)
Itt csak követni tudjuk, hogy mi történik az Alaptörvénnyel, változtatni rajta máshol kell.
